In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [1]:
from google.colab import files
uploaded = files.upload()

Saving fake_job_postings.csv to fake_job_postings.csv

In [3]:
import pandas as pd

df = pd.read_csv(
    "fake_job_postings.csv",
    encoding="latin1",
    engine="python",
    on_bad_lines="skip"
)

df.head()

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI  Environmental Systems Rese...,"EDUCATION: Bachelors or Masters in GIS, busi...",Our culture is anything but corporatewe have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17879 entries, 0 to 17878
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_id               17879 non-null  int64
 1   title                17879 non-null  object
 2   location             17533 non-null  object
 3   department           6333 non-null   object
 4   salary_range         2868 non-null   object
 5   company_profile      14571 non-null  object
 6   description          17878 non-null  object
 7   requirements         15183 non-null  object
 8   benefits             10667 non-null  object
 9   telecommuting        17879 non-null  int64
 10  has_company_logo     17879 non-null  int64
 11  has_questions        17879 non-null  int64
 12  employment_type      14408 non-null  object
 13  required_experience  10829 non-null  object
 14  required_education   9774 non-null   object
 15  industry             12976 non-null  object
 16  function             11424 non-null  object
 17  fraudulent           17879 non-null  int64
dtypes: int64(5), object(13)
memory usage: 2.5+ MB

In [5]:
df.shape

(17879, 18)

In [6]:
df.columns

Index(['job_id', 'title', 'location', 'department', 'salary_range',
       'company_profile', 'description', 'requirements', 'benefits',
       'telecommuting', 'has_company_logo', 'has_questions', 'employment_type',
       'required_experience', 'required_education', 'industry', 'function',
       'fraudulent'],
      dtype='object')

In [7]:
df.isnull().sum()

job_id                     0
title                      0
location                 346
department             11546
salary_range           15011
company_profile         3308
description                1
requirements            2696
benefits                7212
telecommuting              0
has_company_logo           0
has_questions              0
employment_type         3471
required_experience     7050
required_education      8105
industry                4903
function                6455
fraudulent                 0
dtype: int64

In [8]:
df.describe()

,job_id,telecommuting,has_company_logo,has_questions,fraudulent
count,17879.000000,17879.000000,17879.000000,17879.000000,17879.000000
mean,8940.287600,0.042899,0.795291,0.491694,0.048437
std,5161.721958,0.202636,0.403500,0.499945,0.214693
min,1.000000,0.000000,0.000000,0.000000,0.000000
25%,4470.500000,0.000000,1.000000,0.000000,0.000000
50%,8940.000000,0.000000,1.000000,0.000000,0.000000
75%,13410.500000,0.000000,1.000000,1.000000,0.000000
max,17880.000000,1.000000,1.000000,1.000000,1.000000

In [9]:
df["fraudulent"].value_counts()

fraudulent
0    17013
1      866
Name: count, dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
# Step 1 - Import Libraries


import pandas as pd
import numpy as np

In [12]:
# ==========================================
# Step 2 - Load Dataset
# ==========================================

df = pd.read_csv(
    "fake_job_postings.csv",
    encoding="latin1",
    engine="python",
    on_bad_lines="skip"
)

In [13]:
# Number of rows and columns

df.shape

(17879, 18)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17879 entries, 0 to 17878
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_id               17879 non-null  int64
 1   title                17879 non-null  object
 2   location             17533 non-null  object
 3   department           6333 non-null   object
 4   salary_range         2868 non-null   object
 5   company_profile      14571 non-null  object
 6   description          17878 non-null  object
 7   requirements         15183 non-null  object
 8   benefits             10667 non-null  object
 9   telecommuting        17879 non-null  int64
 10  has_company_logo     17879 non-null  int64
 11  has_questions        17879 non-null  int64
 12  employment_type      14408 non-null  object
 13  required_experience  10829 non-null  object
 14  required_education   9774 non-null   object
 15  industry             12976 non-null  object
 16  function             11424 non-null  object
 17  fraudulent           17879 non-null  int64
dtypes: int64(5), object(13)
memory usage: 2.5+ MB

In [15]:
missing = (df.isnull().sum()/len(df))*100

missing.sort_values(ascending=False)

salary_range           83.958834
department             64.578556
required_education     45.332513
benefits               40.337827
required_experience    39.431736
function               36.103809
industry               27.423234
employment_type        19.413837
company_profile        18.502153
requirements           15.079143
location                1.935231
description             0.005593
title                   0.000000
job_id                  0.000000
telecommuting           0.000000
has_questions           0.000000
has_company_logo        0.000000
fraudulent              0.000000
dtype: float64

In [16]:
#Select Important Columns
columns = [
    "title",
    "company_profile",
    "description",
    "requirements",
    "benefits",
    "fraudulent"
]

df = df[columns]

df.head()

,title,company_profile,description,requirements,benefits,fraudulent
0,Marketing Intern,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0
1,Customer Service - Cloud Video Production,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0
2,Commissioning Machinery Assistant (CMA),Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0
3,Account Executive - Washington DC,Our passion for improving quality of life thro...,THE COMPANY: ESRI  Environmental Systems Rese...,"EDUCATION: Bachelors or Masters in GIS, busi...",Our culture is anything but corporatewe have ...,0
4,Bill Review Manager,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0

In [17]:
#Check Missing Values Again
df.isnull().sum()

title                 0
company_profile    3308
description           1
requirements       2696
benefits           7212
fraudulent            0
dtype: int64

In [18]:
# Fill Missing Values
df["company_profile"] = df["company_profile"].fillna("")
df["description"] = df["description"].fillna("")
df["requirements"] = df["requirements"].fillna("")
df["benefits"] = df["benefits"].fillna("")

In [19]:
# Check Again
df.isnull().sum()

title              0
company_profile    0
description        0
requirements       0
benefits           0
fraudulent         0
dtype: int64

In [20]:
# Combine Text Columns
df["text"] = (
    df["title"] + " " +
    df["company_profile"] + " " +
    df["description"] + " " +
    df["requirements"] + " " +
    df["benefits"]
)

In [22]:
#Check New Column
df[["text", "fraudulent"]].head()

                                                text  fraudulent
0  Marketing Intern We're Food52, and we've creat...           0
1  Customer Service - Cloud Video Production 90 S...           0
2  Commissioning Machinery Assistant (CMA) Valor ...           0
3  Account Executive - Washington DC Our passion ...           0
4  Bill Review Manager SpotSource Solutions LLC i...           0

In [23]:
#Convert Text to Lowercase
df["text"] = df["text"].str.lower()

df["text"].head()

0    marketing intern we're food52, and we've creat...
1    customer service - cloud video production 90 s...
2    commissioning machinery assistant (cma) valor ...
3    account executive - washington dc our passion ...
4    bill review manager spotsource solutions llc i...
Name: text, dtype: object

In [24]:
#Remove Punctuation
import re

df["text"] = df["text"].apply(lambda x: re.sub(r"[^\w\s]", "", x))

df["text"].head()

0    marketing intern were food52 and weve created ...
1    customer service  cloud video production 90 se...
2    commissioning machinery assistant cma valor se...
3    account executive  washington dc our passion f...
4    bill review manager spotsource solutions llc i...
Name: text, dtype: object

In [25]:
# Remove Numbers
df["text"] = df["text"].apply(lambda x: re.sub(r"\d+", "", x))

df["text"].head()

0    marketing intern were food and weve created a ...
1    customer service  cloud video production  seco...
2    commissioning machinery assistant cma valor se...
3    account executive  washington dc our passion f...
4    bill review manager spotsource solutions llc i...
Name: text, dtype: object

In [27]:
# Remove Extra Spaces
df["text"] = df["text"].apply(lambda x: " ".join(x.split()))

df["text"].head()

0    marketing intern were food and weve created a ...
1    customer service cloud video production second...
2    commissioning machinery assistant cma valor se...
3    account executive washington dc our passion fo...
4    bill review manager spotsource solutions llc i...
Name: text, dtype: object

In [29]:
#Import NLTK
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [30]:
#Load Stopwords
from nltk.corpus import stopwords
stop_words = set(stopwords.words("english"))

In [32]:
#Remove Stopwords
df["text"] = df["text"].apply(
    lambda x: " ".join(
        word for word in x.split()
        if word not in stop_words
    )
)

In [33]:
df["text"].head()

0    marketing intern food weve created groundbreak...
1    customer service cloud video production second...
2    commissioning machinery assistant cma valor se...
3    account executive washington dc passion improv...
4    bill review manager spotsource solutions llc g...
Name: text, dtype: object

In [34]:
# ==========================================
# Import TF-IDF Vectorizer
# ==========================================

from sklearn.feature_extraction.text import TfidfVectorizer

In [35]:
# ==========================================
#  Create TF-IDF Vectorizer
# max_features = 5000
# ==========================================

# Convert text into numerical vectors

vectorizer = TfidfVectorizer(max_features=5000)

In [38]:
# ==========================================
# Convert Text into TF-IDF Features
# ==========================================

# X contains input features
X = vectorizer.fit_transform(df["text"])

In [40]:
# ==========================================
# Create Target Variable
# ==========================================

# y contains labels
# 0 = Genuine Job
# 1 = Fake Job

y = df["fraudulent"]

In [41]:
# ==========================================
# Display Shape of Dataset
# ==========================================

print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (17879, 5000)
Shape of y: (17879,)

In [42]:
# ==========================================
# Display TF-IDF Matrix
# ==========================================

print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2548089 stored elements and shape (17879, 5000)>
  Coords	Values
  (0, 2699)	0.06173756100871826
  (0, 2360)	0.058343236943506266
  (0, 1833)	0.5561570236547863
  (0, 4895)	0.04653003133974176
  (0, 1058)	0.04950036805981301
  (0, 2008)	0.07015600263082622
  (0, 400)	0.1230789599426362
  (0, 997)	0.2919134266522488
  (0, 4100)	0.04127448614456151
  (0, 4373)	0.05442702092717873
  (0, 921)	0.11186971976112929
  (0, 669)	0.07434173309937495
  (0, 2115)	0.12228265584272931
  (0, 998)	0.15902899386702893
  (0, 1962)	0.04469738352823583
  (0, 1610)	0.04726784009930325
  (0, 2905)	0.031632365862758034
  (0, 3014)	0.02690461671937843
  (0, 4558)	0.03696780954643039
  (0, 1413)	0.1304669419534256
  (0, 590)	0.021715392204844555
  (0, 1497)	0.033790769880055804
  (0, 4442)	0.03447870630897049
  (0, 1822)	0.0420051938009655
  (0, 4740)	0.03041130007258647
  :	:
  (17878, 3543)	0.05581577517513165
  (17878, 4281)	0.05447665151915969
  (17878, 4179)	0.05036331742693269
  (17878, 1088)	0.055121392024480936
  (17878, 3941)	0.05157515425739158
  (17878, 4903)	0.056374047739370395
  (17878, 4803)	0.05563710541534032
  (17878, 1080)	0.06386024419533937
  (17878, 4057)	0.05537556455146285
  (17878, 2925)	0.05417077381900139
  (17878, 2403)	0.0567663933806112
  (17878, 498)	0.054554769132920414
  (17878, 405)	0.05656808807873455
  (17878, 2585)	0.05656808807873455
  (17878, 4178)	0.056374047739370395
  (17878, 2960)	0.05656808807873455
  (17878, 603)	0.05656808807873455
  (17878, 4784)	0.056374047739370395
  (17878, 4878)	0.05609059422834774
  (17878, 636)	0.05609059422834774
  (17878, 1110)	0.05656808807873455
  (17878, 235)	0.05656808807873455
  (17878, 4648)	0.05656808807873455
  (17878, 1856)	0.05656808807873455
  (17878, 4909)	0.05618409276481553

In [43]:
# Import Train Test Split

from sklearn.model_selection import train_test_split

In [44]:
# Split Dataset into Training and Testing Data

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [45]:
# Display Training and Testing Shapes

print("X_train Shape :", X_train.shape)
print("X_test Shape :", X_test.shape)
print("y_train Shape :", y_train.shape)
print("y_test Shape :", y_test.shape)

X_train Shape : (14303, 5000)
X_test Shape : (3576, 5000)
y_train Shape : (14303,)
y_test Shape : (3576,)

In [46]:
# Import Logistic Regression

from sklearn.linear_model import LogisticRegression

In [63]:
# Create Balanced Logistic Regression Model

model = LogisticRegression(
    class_weight="balanced",
    random_state=42,
    max_iter=1000
)

In [64]:
# Train the Model

model.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

In [65]:
# Predict Test Data

y_pred = model.predict(X_test)

In [50]:
# Display Predicted Values

print(y_pred)

[0 0 0 ... 0 0 0]

In [66]:
# Import Accuracy Score

from sklearn.metrics import accuracy_score

In [67]:
# Calculate Model Accuracy

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy :", accuracy)

Accuracy : 0.9667225950782998

In [53]:
# Import Confusion Matrix

from sklearn.metrics import confusion_matrix

In [54]:
# Generate Confusion Matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[3391    0]
 [ 103   82]]

In [55]:
# Import Classification Report

from sklearn.metrics import classification_report

In [68]:
# Display Classification Report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.97      0.98      3391
           1       0.63      0.89      0.73       185

    accuracy                           0.97      3576
   macro avg       0.81      0.93      0.86      3576
weighted avg       0.97      0.97      0.97      3576

In [57]:
# Import Joblib Library

import joblib

In [69]:
# Save Trained Model

joblib.dump(model, "jobshield_model.pkl")

['jobshield_model.pkl']

In [59]:
# Save TF-IDF Vectorizer

joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

['tfidf_vectorizer.pkl']

In [60]:
# Display Saved Files

import os

print(os.listdir())

['.config', 'tfidf_vectorizer.pkl', 'jobshield_model.pkl', 'fake_job_postings.csv', 'sample_data']

In [70]:
import joblib

# Save trained model
joblib.dump(model, "jobshield_model.pkl")

# Save TF-IDF vectorizer
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

['tfidf_vectorizer.pkl']

In [71]:
from google.colab import files

files.download("jobshield_model.pkl")
files.download("tfidf_vectorizer.pkl")